[alembic]
script_location = alembic
sqlalchemy.url = postgresql+asyncpg://shop:shop@postgres:5432/shopthereel

[loggers]
keys = root

[handlers]
keys = console

[logger_root]
level = WARN
handlers = console
qualname =
